version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: apnatrack-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --requirepass redis_pass --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - apnatrack-network

  mongo:
    image: mongo:6
    container_name: Tracker
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - apnatrack-network

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: Tracker-otel-collector
    restart: unless-stopped
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8888:8888"
      - "8889:8889"
    volumes:
      - ./otel.yml:/etc/otelcol-contrib/otel-collector.yaml
    command: ["--config=/etc/otelcol-contrib/otel-collector.yaml"]
    networks:
      - apnatrack-network

volumes:
  redis_data:
    driver: local
  mongo_data:
    driver: local

networks:
  apnatrack-network:
    driver: bridge
